# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(default=0)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestWhole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='testwhole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_pass.TestWhole'),
        ),
        migrations.AddField(
            model_name='option',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_pass.Task'),
        ),
    ]
